### ISSUE TITLE
Very long delay from stopping video to GUI loading

### ISSUE THREAD

**Issue by winedog** [TPX01/skin.quartz.krypton#17]
Tried this on Kodi 17.3 on my Odroid C2 and when this skin is active and I stop playing a video there is about a 45s lag with a black screen before the Kodi UI loads up again.  Switching away from this skin resolves the problem so it does seem specific to Quartz

**Comment by TPX01** [comment]
I've noticed the same issue! Do you have some fresh logs of it?

**Comment by TPX01** [comment]
cannot reproduce this issue anymore
